### ISSUE TITLE
Chocolately Support Wrap Up

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/product#138]
**Tasks**

- [ ] https://github.com/AntelopeIO/DUNE/issues/91
- [ ] https://github.com/AntelopeIO/DUNE/issues/95
- [ ] https://github.com/AntelopeIO/DUNE/issues/109
- [ ] https://github.com/AntelopeIO/DUNE/issues/144
