### ISSUE TITLE
Enable greater parallelization of concurrent WASM executions

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/product#149]
Parallelization of read only transactions is limited by the number of concurrent WASM executions that can be supported by Leap. There are resource limits that bound the number of concurrent WASM executions allowed. This epic focusses on changes to eos-vm  runtimes (for example: interpreter, JIT, and OC), as well as further optimizations within Leap to increase the number of concurrent WASM executions that Leap can support.

```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/product/pull/161
- [ ] https://github.com/AntelopeIO/leap/issues/1159
- [ ] https://github.com/AntelopeIO/leap/issues/1119
- [ ] https://github.com/AntelopeIO/eos-vm/issues/7
- [ ] https://github.com/AntelopeIO/eos-vm/issues/17
- [ ] https://github.com/AntelopeIO/leap/issues/1456
- [ ] https://github.com/AntelopeIO/leap/issues/1158
- [ ] https://github.com/AntelopeIO/leap/issues/645
- [ ] https://github.com/AntelopeIO/leap/issues/1257
- [ ] https://github.com/AntelopeIO/leap/issues/1256
- [ ] https://github.com/AntelopeIO/leap/issues/801
```

**Comment by linh2931** [comment]
The design document is https://github.com/eosnetworkfoundation/product/blob/read_only_trx_memory/transactions/read-only/memory.md.

**Comment by BenjaminGormanPMP** [comment]
@bhazzard and @stephenpdeos can you review Lin's document and provide next steps?  Thanks.
Design document https://github.com/eosnetworkfoundation/product/blob/read_only_trx_memory/transactions/read-only/memory.md.

**Comment by BenjaminGormanPMP** [comment]
Closed. All tasks assigned to @linh2931 were completed.
