### ISSUE TITLE
Onboard to EVM FE

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/product#167]
```[tasklist]
### Epics
- [ ] https://github.com/eosnetworkfoundation/product/issues/168
- [ ] https://github.com/eosnetworkfoundation/product/issues/169
- [ ] https://github.com/eosnetworkfoundation/product/issues/170
```
