### ISSUE TITLE
Onboard to Bridge FE

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/product#168]
The US FE team needs to onboard to the EOS EVM project, including the [bridge](https://github.com/eosnetworkfoundation/evm-bridge-frontend)

```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/64
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/65
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/66
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/67
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/68
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/69
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/70
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/71
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/76
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/75
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/73
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/74
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/77
- [ ] https://github.com/eosnetworkfoundation/frontend-engineering/issues/79
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-frontend/issues/18
```
