### ISSUE TITLE
EOS EVM Performance Harness

### ISSUE THREAD

**Issue by bhazzard** [eosnetworkfoundation/product#186]
### Short Description
As an ENF developer, I want the performance/regression harness to have support for EOS EVM, so I can use it to test EOS EVM performance.

### What
This epic focuses on extending the Performance Harness and Regression Harness to support EOS EVM, as well as creating performance tests specifically for swaps. The objective is to allow for repeatable performance tests, without directly coupling the performance harness and EOS EVM.

### Why
This is a prerequisite to being able to run EOS EVM Performance Regression Tests or Optimized EOS EVM Performance Benchmarks.
```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/product/issues/187
- [ ] https://github.com/eosnetworkfoundation/product/issues/188
- [ ] https://github.com/eosnetworkfoundation/product/issues/189
```
