### ISSUE TITLE
Expanded Wallet Support for Trustless Bridge

### ISSUE THREAD

**Issue by stephenpdiesel** [eosnetworkfoundation/product#196]
```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-frontend/issues/35
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-frontend/issues/52
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-frontend/issues/59
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-frontend/issues/68
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-frontend/issues/67
```
