### ISSUE TITLE
Silkworm Version Upgrade

### ISSUE THREAD

**Issue by stephenpdiesel** [eosnetworkfoundation/product#208]
```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/eos-evm/issues/592
- [ ] https://github.com/eosnetworkfoundation/eos-evm/issues/617
- [ ] https://github.com/eosnetworkfoundation/eos-evm/issues/457
- [ ] https://github.com/eosnetworkfoundation/eos-evm-internal/issues/42
```
