### ISSUE TITLE
0.6.0 Maintenance

### ISSUE THREAD

**Issue by stephenpdiesel** [eosnetworkfoundation/product#249]
```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/silkworm/issues/41
- [ ] https://github.com/eosnetworkfoundation/silkworm/issues/42
- [ ] https://github.com/eosnetworkfoundation/silkworm/issues/43
- [ ] https://github.com/eosnetworkfoundation/eos-evm-node/issues/28
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-contracts/issues/23
- [ ] https://github.com/eosnetworkfoundation/eos-evm/issues/662
- [ ] https://github.com/eosnetworkfoundation/silkworm/issues/79
```
