### ISSUE TITLE
Coin-centric Egress Fee Model

### ISSUE THREAD

**Issue by stephenpdiesel** [eosnetworkfoundation/product#269]
```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-contracts/issues/29
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-contracts/issues/35
```

```[tasklist]
### FE Tasks
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-frontend/issues/70
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-frontend/issues/75
```
