### ISSUE TITLE
Instant Finality Prototype

### ISSUE THREAD

**Issue by bhazzard** [eosnetworkfoundation/product#271]
Antelope core protocol developers are implementing a working prototype of Instant Finality to uncover potential implementation challenges quickly and adjust the design as necessary.

---

## Goals

- Finalize IF algorithms and test in target environments.
- Quickly complete IF implementation and identify issues
- Code not for final product release, but reuse in production version is expected
- Explore features beyond what Leap currently provides to uncover unknown challenges

## Deliverables
Completion of the prototype stage requires the following deliverables to be met:

- Design Document
- Prototype Implementation in Leap
- Prototype Implementation in Reference Contracts
- Prototype Implementation of Finalizer Client
- Prototype implementation of finality advancement proof validation in IBC contracts
- Prototype implementation of finality violation proofs contracts
- Test transition from the old consensus algorithm to IF on 2 testnets
- Demonstrate IBC between two testnets
- Mathematical proofs

```[tasklist]
### Tasks
- [ ] https://github.com/AntelopeIO/leap/issues/1508
- [ ] https://github.com/AntelopeIO/cdt/issues/245
- [ ] https://github.com/AntelopeIO/reference-contracts/issues/26
- [ ] https://github.com/AntelopeIO/reference-contracts/issues/37
- [ ] https://github.com/AntelopeIO/cdt/issues/271
- [ ] https://github.com/AntelopeIO/leap/issues/2110
- [ ] https://github.com/AntelopeIO/spring/issues/92
```
