### ISSUE TITLE
Additional EOS Native Token Bridging Support v1

### ISSUE THREAD

**Issue by stephenpdiesel** [eosnetworkfoundation/product#276]
```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-frontend/issues/79
- [ ] https://github.com/eosnetworkfoundation/eos-evm-internal/issues/76
- [ ] https://github.com/eosnetworkfoundation/eos-evm-internal/issues/80
```
