### ISSUE TITLE
Spring Upgrade Compatibility

### ISSUE THREAD

**Issue by stephenpdiesel** [eosnetworkfoundation/product#289]
```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/eos-evm-node/issues/223
- [ ] https://github.com/eosnetworkfoundation/eos-evm-node/issues/224
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-contracts/issues/43
- [ ] https://github.com/eosnetworkfoundation/eos-evm-contract/issues/717
```
