### ISSUE TITLE
Tokenomics updates Phase 2: REX 2.0

### ISSUE THREAD

**Issue by stephenpdiesel** [eosnetworkfoundation/product#290]
```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/eos-system-contracts/issues/133
- [ ] https://github.com/eosnetworkfoundation/eos-system-contracts/issues/118
- [ ] https://github.com/eosnetworkfoundation/eos-system-contracts/issues/134
```
