### ISSUE TITLE
Instant Finality

### ISSUE THREAD

**Issue by stephenpdiesel** [eosnetworkfoundation/product#39]
See RFP https://github.com/eosnetworkfoundation/Coalition-RFPs/blob/main/2022%2004%20RFP%20-%20Faster%20Finality.pdf
```[tasklist]
### Tasks
- [x] https://github.com/AntelopeIO/leap/issues/1126
- [x] https://github.com/AntelopeIO/leap/issues/1413
- [x] https://github.com/AntelopeIO/cdt/issues/202
- [ ] https://github.com/AntelopeIO/cdt/issues/251
- [ ] https://github.com/eosnetworkfoundation/product/issues/271
- [ ] https://github.com/AntelopeIO/reference-contracts/issues/24
- [ ] https://github.com/AntelopeIO/leap/issues/2260
- [ ] https://github.com/eosnetworkfoundation/eos-system-contracts/issues/85
- [ ] https://github.com/eosnetworkfoundation/product/issues/286
- [ ] https://github.com/AntelopeIO/spring/issues/93
- [ ] https://github.com/AntelopeIO/spring/issues/94
```
