### ISSUE TITLE
Leap-util MVP

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/product#45]
See proposal https://github.com/eosnetworkfoundation/product/blob/main/cli/proposals/leap-util.md

Tasks
- [X] https://github.com/AntelopeIO/leap/issues/141
- [X] https://github.com/AntelopeIO/leap/issues/143
- [X] https://github.com/AntelopeIO/leap/issues/144
- [x] https://github.com/AntelopeIO/leap/issues/142
- [x] https://github.com/AntelopeIO/leap/issues/282

**Comment by stephenpdeos** [comment]
Reaming subtasks are being added to enhancements
