### ISSUE TITLE
Parallelize Speculative Read-Only Transaction Execution

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/product#95]
#### Opportunity: What are the needs of our target user groups?

Currently transactions are executed in a single thread. To take advantage of multi-core architecture, executing speculative transactions in multiple threads would improve performance.

#### Target audience: Who is the target audience and why? 

API `nodeos` operators and users.

#### Strategic alignment: How does this problem align with our core strategic pillars?
Performance

#### Solution name: How should we refer to this product opportunity?

Parallelize Speculative Transaction Execution

#### Assumptions

Only `irreversible` and `head` are supported in DB `read-mode` configuration.

#### Features/Epics

A possible solution is being investigated.

`nodeos` runs in one of two modes between which it cycles rapidly (to maintain good latency on fulfilling the requests),  _read-only mode_, and _exclusive write mode_:

- In _exclusive write mode_,  `nodeos` quickly syncs to the latest available blocks that were being queued up in the fork database. Transactions received during this mode are queued in a transaction queue.
- In _read-only mode_, block syncing would be paused to ensure nothing is written to chainbase. Transactions in the transaction queue are dispatched to a thread pool to access chainbase in parallel.

Several design decisions need to be made in this approach.

- A transaction can potentially modify the state it is accessing. It needs to see its own side-effects, but still be isolated from the side-effects of any other concurrently executing transactions. For each transaction, we will create a separate simulated state from the common LIB or head such that the transaction works on this simulated state only. After the transaction execution is finished, the simulated state is discarded. Research is needed on how to support this in Chainbase.
- As it gets close to the point where transition from _read-only_ to _exclusive write mode_ is expected, additional requests should not be dispatched to the thread pool. Furthermore, some existing threads will run for too long. At that point they will be forcefully killed and re-queued so that they can be processed again in the next read cycle. Once all read threads have stopped, the _exclusive write mode_ is transitioned.
- Duration or ratio of _read-only mode_ and _exclusive write mode_ can be configured. Ideally, those configurations serve as max values. When no more read requests are queued, control can be transitioned to  _exclusive write mode_, and vice versa.

#### Additional tasks
- [x]  https://github.com/AntelopeIO/leap/issues/295
- [x] https://github.com/AntelopeIO/leap/issues/357
- [x] https://github.com/AntelopeIO/leap/issues/440
- [x] https://github.com/AntelopeIO/leap/issues/478
- [x] https://github.com/AntelopeIO/leap/issues/479
- [x] https://github.com/AntelopeIO/leap/issues/480
- [x] https://github.com/AntelopeIO/leap/issues/482
- [x] https://github.com/AntelopeIO/leap/issues/511
- [x] https://github.com/AntelopeIO/leap/issues/526
- [x] https://github.com/AntelopeIO/leap/issues/529
- [x] https://github.com/AntelopeIO/leap/issues/170

### Open questions

**Comment by linh2931** [comment]
<img width="1074" alt="Screen Shot 2022-10-25 at 9 11 21 PM" src="https://user-images.githubusercontent.com/107445030/197911402-c7d0a6b5-566c-4f08-978d-4e723d2174da.png">

**Comment by jbuice** [comment]
Huge +1 on this.

**Comment by bhazzard** [comment]
All tasks complete, moving this to "Transition to Operations"
